version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      selenium:
        condition: service_healthy
    command: pytest --browser=remote ui/tests/

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:4444/wd/hub || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
